"""initialize normalized market data model

Revision ID: 310b4bb61557
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "310b4bb61557"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cs2_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("market_hash_name", sa.String(length=512), nullable=False),
        sa.Column("weapon", sa.String(length=128), nullable=True),
        sa.Column("skin", sa.String(length=256), nullable=True),
        sa.Column("exterior", sa.String(length=64), nullable=True),
        sa.Column("stattrak", sa.Boolean(), nullable=True),
        sa.Column("souvenir", sa.Boolean(), nullable=True),
        sa.Column("float_value", sa.Numeric(precision=24, scale=20), nullable=True),
        sa.Column("paint_index", sa.Integer(), nullable=True),
        sa.Column("paint_seed", sa.Integer(), nullable=True),
        sa.Column("doppler_phase", sa.String(length=64), nullable=True),
        sa.Column("fade_percentage", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("inspect_link", sa.String(length=2048), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("mode IN ('demo', 'live')"),
        sa.CheckConstraint(
            "fade_percentage IS NULL OR (fade_percentage >= 0 AND fade_percentage <= 100)"
        ),
        sa.CheckConstraint("float_value IS NULL OR (float_value >= 0 AND float_value <= 1)"),
        sa.CheckConstraint("paint_seed IS NULL OR (paint_seed >= 0 AND paint_seed <= 1000)"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mode", "platform", "external_id", name="uq_item_source"),
    )
    op.create_index(
        op.f("ix_cs2_items_market_hash_name"), "cs2_items", ["market_hash_name"], unique=False
    )
    op.create_index(op.f("ix_cs2_items_mode"), "cs2_items", ["mode"], unique=False)
    op.create_table(
        "market_sync_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=1024), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mode", "platform", name="uq_sync_source"),
    )
    op.create_table(
        "pattern_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skin", sa.String(length=256), nullable=False),
        sa.Column("paint_seed", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.String(length=64), nullable=True),
        sa.Column("premium_estimate", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=2048), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 100"),
        sa.CheckConstraint("paint_seed >= 0 AND paint_seed <= 1000"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("market_hash_name", sa.String(length=512), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_eur_reference", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("fx_rate", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("fx_rate_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fx_rate_source", sa.String(length=512), nullable=True),
        sa.Column("observation_type", sa.String(length=20), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.CheckConstraint("mode IN ('demo', 'live')"),
        sa.CheckConstraint(
            "observation_type IN ('LISTING','SALE','BUY_ORDER','TRADE_VALUE','AGGREGATE')"
        ),
        sa.CheckConstraint("price >= 0"),
        sa.CheckConstraint("volume IS NULL OR volume >= 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_observation_fingerprint"),
    )
    op.create_index(
        "ix_observation_lookup",
        "price_observations",
        ["mode", "market_hash_name", "timestamp"],
        unique=False,
    )
    op.create_table(
        "item_stickers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=True),
        sa.Column("wear", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column("steam_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("estimated_applied_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.CheckConstraint("wear IS NULL OR (wear >= 0 AND wear <= 1)"),
        sa.ForeignKeyConstraint(["item_id"], ["cs2_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_stickers_item_id"), "item_stickers", ["item_id"], unique=False)
    op.create_table(
        "market_listings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("price_original", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency_original", sa.String(length=3), nullable=False),
        sa.Column("price_eur_reference", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("fx_rate", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("fx_rate_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fx_rate_source", sa.String(length=512), nullable=True),
        sa.Column("seller_type", sa.String(length=64), nullable=True),
        sa.Column("listing_url", sa.String(length=2048), nullable=True),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.CheckConstraint("mode IN ('demo', 'live')"),
        sa.CheckConstraint("price_original >= 0"),
        sa.ForeignKeyConstraint(["item_id"], ["cs2_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mode", "platform", "external_id", name="uq_listing_source"),
    )
    op.create_index(
        op.f("ix_market_listings_item_id"), "market_listings", ["item_id"], unique=False
    )
    op.create_index(op.f("ix_market_listings_mode"), "market_listings", ["mode"], unique=False)
    op.create_index(
        op.f("ix_market_listings_observed_at"), "market_listings", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_listings_platform"), "market_listings", ["platform"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_listings_platform"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_observed_at"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_mode"), table_name="market_listings")
    op.drop_index(op.f("ix_market_listings_item_id"), table_name="market_listings")
    op.drop_table("market_listings")
    op.drop_index(op.f("ix_item_stickers_item_id"), table_name="item_stickers")
    op.drop_table("item_stickers")
    op.drop_index("ix_observation_lookup", table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_table("pattern_rules")
    op.drop_table("market_sync_states")
    op.drop_index(op.f("ix_cs2_items_mode"), table_name="cs2_items")
    op.drop_index(op.f("ix_cs2_items_market_hash_name"), table_name="cs2_items")
    op.drop_table("cs2_items")
    # ### end Alembic commands ###
