export interface AuthConfig {
  adminUsername: string;
  adminPasswordHash: string;
  sessionSecret: string;
  sessionCookieSecure: boolean;
  sessionTtlSeconds: number;
  loginRateLimitMaxAttempts: number;
  loginRateLimitWindowSeconds: number;
}

type Env = Record<string, string | undefined>;

export type AuthConfigResult =
  | { ok: true; config: AuthConfig }
  | { ok: false; errors: string[] };

export function readAuthConfig(env: Env = process.env): AuthConfigResult {
  const errors: string[] = [];
  const adminUsername = env.ADMIN_USERNAME?.trim() ?? "";
  const adminPasswordHash = env.ADMIN_PASSWORD_HASH?.trim() ?? "";
  const sessionSecret = env.SESSION_SECRET?.trim() ?? "";
  const sessionTtlSeconds = integerSetting(env.SESSION_TTL_SECONDS, 28_800);
  const loginRateLimitMaxAttempts = integerSetting(env.LOGIN_RATE_LIMIT_MAX_ATTEMPTS, 5);
  const loginRateLimitWindowSeconds = integerSetting(env.LOGIN_RATE_LIMIT_WINDOW_SECONDS, 900);
  const sessionCookieSecure = booleanSetting(env.SESSION_COOKIE_SECURE, false);

  if (!adminUsername) errors.push("ADMIN_USERNAME is required.");
  if (/[\u0000-\u001f]/.test(adminUsername) || adminUsername.length > 64) {
    errors.push("ADMIN_USERNAME is invalid.");
  }
  if (!adminPasswordHash) errors.push("ADMIN_PASSWORD_HASH is required.");
  if (adminPasswordHash && !/^scrypt\$16384\$8\$1\$[A-Za-z0-9_-]{22}\$[A-Za-z0-9_-]{86}$/.test(adminPasswordHash)) {
    errors.push("ADMIN_PASSWORD_HASH must be generated by the project hash tool.");
  }
  if (sessionSecret.length < 32) errors.push("SESSION_SECRET must contain at least 32 characters.");
  if (sessionTtlSeconds < 300 || sessionTtlSeconds > 604_800) {
    errors.push("SESSION_TTL_SECONDS must be between 300 and 604800.");
  }
  if (loginRateLimitMaxAttempts < 1 || loginRateLimitMaxAttempts > 50) {
    errors.push("LOGIN_RATE_LIMIT_MAX_ATTEMPTS must be between 1 and 50.");
  }
  if (loginRateLimitWindowSeconds < 60 || loginRateLimitWindowSeconds > 86_400) {
    errors.push("LOGIN_RATE_LIMIT_WINDOW_SECONDS must be between 60 and 86400.");
  }

  if (errors.length) return { ok: false, errors };
  return {
    ok: true,
    config: {
      adminUsername,
      adminPasswordHash,
      sessionSecret,
      sessionCookieSecure,
      sessionTtlSeconds,
      loginRateLimitMaxAttempts,
      loginRateLimitWindowSeconds,
    },
  };
}

export function hasSessionSecret(env: Env = process.env): string | null {
  const value = env.SESSION_SECRET?.trim();
  return value && value.length >= 32 ? value : null;
}

function integerSetting(value: string | undefined, fallback: number): number {
  if (!value?.trim()) return fallback;
  const parsed = Number(value);
  return Number.isInteger(parsed) ? parsed : Number.NaN;
}

function booleanSetting(value: string | undefined, fallback: boolean): boolean {
  if (!value?.trim()) return fallback;
  return ["1", "true", "yes", "on"].includes(value.trim().toLowerCase());
}
