import { describe, expect, it } from "vitest";
import { hashPassword } from "./password";
import { readAuthConfig } from "./auth-config";

const validEnv = () => ({
  ADMIN_USERNAME: "admin",
  ADMIN_PASSWORD_HASH: hashPassword("correct-password", Buffer.alloc(16, 1)),
  SESSION_SECRET: "s".repeat(32),
});

describe("readAuthConfig", () => {
  it("applies safe defaults to a valid configuration", () => {
    const result = readAuthConfig(validEnv());
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.config).toMatchObject({
      adminUsername: "admin",
      sessionCookieSecure: false,
      sessionTtlSeconds: 28_800,
      loginRateLimitMaxAttempts: 5,
      loginRateLimitWindowSeconds: 900,
    });
  });

  it("rejects missing secrets and malformed hashes", () => {
    const result = readAuthConfig({ ADMIN_USERNAME: "admin", ADMIN_PASSWORD_HASH: "scrypt$bad" });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errors).toContain("ADMIN_PASSWORD_HASH must be generated by the project hash tool.");
    expect(result.errors).toContain("SESSION_SECRET must contain at least 32 characters.");
  });
});
